fixes #75
eclipsesource/jsonforms-vuetify-renderers pull request #76
Opened 2022-09-24 18:11 UTC by kchobantonov

Fixes #75

2022-09-24 18:31 UTC, kchobantonov commented
@sdirix please review

2022-10-01 18:11 UTC, kchobantonov commented
@sdirix  I also added the ability to translate the dropdown labels

2022-10-04 08:50 UTC, sdirix commented
Thanks for the PR :heart: , I'll take a look

2022-10-25 10:49 UTC, lucas-koehler requested changes
I added some minor comments.
Something seems to be broken with the enums. See the enum example: https://deploy-preview-76--jsonforms-vuetify-renderers.netlify.app/#/example/enum
If you open the console you can also see errors

2022-10-25 13:28 UTC, kchobantonov commented on example/src/i18n/i18n.ts
> +    let localeTraslations = translations[locale];
@lucas-koehler thanks  - fixed in the next commit

2022-10-25 13:41 UTC, kchobantonov commented
> I added some minor comments. Something seems to be broken with the enums. See the enum example: https://deploy-preview-76--jsonforms-vuetify-renderers.netlify.app/#/example/enum If you open the console you can also see errors. It doesn't seem to find the translation function to translate the item labels:
> 
> ```
> vue.runtime.esm.js:3020 TypeError: e.t is not a function
>     at item-text (app.c5b53e55.js:1:118544)
> ```

thanks for catching this. I will fix in the next commit

2022-10-25 13:43 UTC, kchobantonov commented
@lucas-koehler  please review again - https://deploy-preview-76--jsonforms-vuetify-renderers.netlify.app/#/example/enum

2022-10-26 10:06 UTC, lucas-koehler approved these changes
@kchobantonov Thanks for the updates, LGTM now :)

2022-10-26 10:08 UTC, merged